### ISSUE TITLE
Airflow ETL for CWMS Radar Datasource

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/water#36]

**Comment by adamscarberry** [comment]
Do we want two endpoints and two dags?  One for timeseries and one for location levels?

**Comment by adamscarberry** [comment]
Possible api endpoint results for airflow to determine paths to pull from RADAR:

```
[
    {
        "timeseries": [
            {"project": "Bluestone", "office": "LRH", "type": "pool", "param": "Elev", "path": "Bluestone-Lake.Elev.Inst.15Minutes.0.OBS"},
            {"project": "Bluestone", "office": "LRH", "type": "pool", "param": "Flow", "path": "Bluestone-Lake.Flow.Inst.15Minutes.0.OBS"},
            {"project": "Bluestone", "office": "LRH", "type": "outflow", "param": "Flow", "path": "Bluestone-Outflow.Flow.Inst.15Minutes.0.OBS"},
            {"project": "Bluestone", "office": "LRH", "type": "outflow", "param": "Stage", "path": "Bluestone-Outflow.Flow.Inst.15Minutes.0.OBS"}

        ],
        "location-levels": [
            {"project": "Bluestone", "office": "LRH", "name": "Streambed", "param": "Elev", "path": "Bluestone.Elev.Inst.0.Streambed"},
            {"project": "Bluestone", "office": "LRH", "name": "Top of Dam", "param": "Elev", "path": "Bluestone.Elev.Inst.0.Top of Dam"},
            {"project": "Bluestone", "office": "LRH", "name": "Top of Flood", "param": "Elev", "path": "Top of Flood"}
        ]
    }
]

All offices in single payload.
```

**Comment by adamscarberry** [comment]
The proposed Airflow DAG implementation to load timeseries will group tasks by office.  I had to break out each call to RADAR separately for each tsid (otherwise the service would fail).

Currently each tsid if fetched from RADAR, then when all are successful complete, the single POST back to water-api happens.

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/46494851/191025607-453c6060-9591-4e77-8f02-040e205dc900.png">

🛑 Problem with this single post concept, when all RADAR fetches are not successful, it will wait until that condition is true.  Should one never succeed, the POST will never happen.  It may be required to POST to water-api for every tsid (during each dynamic task).

@brettpalmberg  Thoughts?

**Comment by brettpalmberg** [comment]
> It may be required to POST to water-api for every tsid (during each dynamic task).

I think this works 👍🏻

**Comment by adamscarberry** [comment]
Work has been ongoing for this task, just forgot to update the status here.

Some obstacles were encountered.  Mainly the NWDP and NWDM regional groups complicated the retrieval of timeseries paths and local levels from RADAR since `bounding_office` is not available for those endpoints.  The workaround was to get all locations for each office from the water-api and hit RADAR with a location+'*' to wildcard the search and ensure the results were able to be associate with the individual offices (NWP, NWS, NWW, etc)

Sync Timeseries Paths DAG
- [ ] Develop
- [ ] Stable

Sync Mapped Timeseries Measurements DAG
- [ ] Develop
- [ ] Stable

Sync Levels DAG
- [ ] Develop
- [ ] Stable

Sync Level Values DAG
- [ ] Develop
- [ ] Stable

**Comment by FHanbali** [comment]
Thanks for testing things out guys and for the feedback.  I'll set up a meeting for us to connect with @MikeNeilson, he'll be in tomorrow.

**Comment by adamscarberry** [comment]
This can be closed.  Outstanding DAG issues have been created separately.
