### ISSUE TITLE
Delete Visualization Mappings?

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/water#48]
I accidentally created a visualization mapping for variable `damtop.` instead of `damtop` when I was working on the UI 😃.

![image](https://user-images.githubusercontent.com/29417036/196298120-49aa3e4b-1d5b-496b-827f-9f7a43ed773d.png)

Do we have a way to delete visualization mappings at this time? We could either implement:

1. Delete endpoint
2. Delete mapping objects that are not present in the mapping array on POST.

Going with (2) simplifies things on the UI side, but either works. Let's connect to work through the alternatives.

**Comment by adamscarberry** [comment]
Right now, mapping are deleted by deleting the visualization.

For scenarios where the wrong key was selected for the variable, posting the correct one with the same variable will correct it (on conflict update).

I didn't consider the wrong variable would be provided (since it's not input by the user).  No way to delete that at the moment.

**Comment by brettpalmberg** [comment]
I added an endpoint to facilitate deleting 1 or more Timeseries-Variable mappings for a single chart. The endpoint is `DELETE /providers/{providerSlug}/charts/{chartSlug}/mapping`. Example usage is available in Postman functional tests in branch `feature/v2-locations`.
